services:
    nginx:
        image: nginx:latest #последняя версия
        container_name: nginx-balance
        working_dir: /application
        networks:
            - internal
        ports:
            - "8066:80"
        volumes:
            - ./../:/application
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: .
            dockerfile: php-fpm/Dockerfile
        container_name: php-balance
        working_dir: /application
        networks:
            - internal
        volumes:
            - ./../:/application
            - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - pgsql

    pgsql:
        image: postgres:17
        restart: always
        container_name: pgsql-balance
        environment:
            POSTGRES_DB: balance
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ./pgsql/init:/docker-entrypoint-initdb.d:ro
            - 'postgres_data:/var/lib/postgresql/data'
        networks:
            - internal
        ports:
            - "5441:5432"

volumes:
    postgres_data:
        driver: local
networks:
    internal:
        driver: bridge
